export const BOOK_LIST_REQUEST='BOOK_LIST_REQUEST';
export const BOOK_LIST_SUCCESS='BOOK_LIST_SUCCESS';
export const BOOK_LIST_FAIL='BOOK_LIST_FAIL';

export const BOOK_DETAILS_REQUEST = "BOOK_DETAILS_REQUEST";
export const BOOK_DETAILS_SUCCESS = "BOOK_DETAILS_SUCCESS";
export const BOOK_DETAILS_FAIL = "BOOK_DETAILS_FAIL";

export const BOOK_ADD_REQUEST='BOOK_ADD_REQUEST';
export const BOOK_ADD_SUCCESS='BOOK_ADD_SUCCESS';
export const BOOK_ADD_FAIL='BOOK_ADD_FAIL';

export const FAVORITE_ADD_REQUEST="FAVORITE_ADD_REQUEST";
export const FAVORITE_ADD_SUCCESS="FAVORITE_ADD_SUCCESS";
export const FAVORITE_ADD_FAIL="FAVORITE_ADD_FAIL"

export const FAVORITE_DETAILS_REQUEST="FAVORITE_DETAILS_REQUEST";
export const FAVORITE_DETAILS_SUCCESS="FAVORITE_DETAILS_SUCCESS";
export const FAVORITE_DETAILS_FAIL="FAVORITE_DETAILS_FAIL"


export const MYBOOK_DETAILS_REQUEST="MYBOOK_DETAILS_REQUEST";
export const MYBOOK_DETAILS_SUCCESS="MYBOOK_DETAILS_SUCCESS";
export const MYBOOK_DETAILS_FAIL="MYBOOK_DETAILS_FAIL";

export const MYBOOK_UPDATE_REQUEST="MYBOOK_UPDATE_REQUEST";
export const MYBOOK_UPDATE_SUCCESS="MYBOOK_UPDATE_SUCCESS";
export const MYBOOK_UPDATE_FAIL="MYBOOK_UPDATE_FAIL";

export const MYBOOK_DELETE_REQUEST="MYBOOK_DELETE_REQUEST";
export const MYBOOK_DELETE_SUCCESS="MYBOOK_DELETE_SUCCESS";
export const MYBOOK_DELETE_FAIL="MYBOOK_DELETE_FAIL"